#!/usr/bin/env bash
# This script displays "Best School" 10 times using an until loop
# Initialize a counter
count=0
# Use an until loop to iterate until the counter is equal to 10
until [ $count -eq 10 ]; do
    echo "Best School"
    # Increment the counter
    count=$((count + 1))
done
