#!/usr/bin/env bash
# This script displays different messages based on the iteration number.
# Use a while loop to iterate from 1 to 10
count=1
while [ $count -le 10 ]; do
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
   ((count++))
done
